wandb_version: 1

obs_keys:
  desc: null
  value:
  - hand_qpos
  - hand_qvel
  - obj_pos
  - goal_pos
  - pos_err
  - obj_rot
  - goal_rot
  - rot_err
weighted_reward_keys:
  desc: null
  value:
    pos_dist: 15.0
    rot_dist: 0
    act_reg: 0.01
    solved: 100.0
    drop: -1.0
    keep_time: -200.0
normalize_act:
  desc: null
  value: true
frame_skip:
  desc: null
  value: 5
pos_th:
  desc: null
  value: 0.1
rot_th:
  desc: null
  value: .inf
target_xyz_range:
  desc: null
  value:
    high:
    - 0.3
    - -0.1
    - 0.9
    low:
    - 0.0
    - -0.45
    - 0.9
_wandb:
  desc: null
  value:
    code_path: code/src/main_relocate.py
    python_version: 3.10.12
    cli_version: 0.15.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698303552.94559
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.15.11
      8:
      - 5
      13: linux-x86_64
