wandb_version: 1

weighted_reward_keys:
  desc: null
  value:
    pos_dist: 10.0
    rot_dist: 1.0
    act_reg: 0.01
    solved: 10000
    drop: -10.0
normalize_act:
  desc: null
  value: true
frame_skip:
  desc: null
  value: 5
pos_th:
  desc: null
  value: 0.1
rot_th:
  desc: null
  value: .inf
qpos_noise_range:
  desc: null
  value: 0.01
target_xyz_range:
  desc: null
  value:
    high:
    - 0.3
    - -0.1
    - 1.05
    low:
    - 0.0
    - -0.45
    - 0.9
target_rxryrz_range:
  desc: null
  value:
    high:
    - 0.2
    - 0.2
    - 0.2
    low:
    - -0.2
    - -0.2
    - -0.2
obj_xyz_range:
  desc: null
  value:
    high:
    - 0.1
    - -0.15
    - 1.0
    low:
    - -0.1
    - -0.35
    - 1.0
obj_geom_range:
  desc: null
  value:
    high:
    - 0.025
    - 0.025
    - 0.025
    low:
    - 0.015
    - 0.015
    - 0.015
obj_mass_range:
  desc: null
  value:
    high: 0.2
    low: 0.05
obj_friction_range:
  desc: null
  value:
    high:
    - 1.2
    - 0.006
    - 0.00012
    low:
    - 0.8
    - 0.004
    - 8.0e-05
_wandb:
  desc: null
  value:
    code_path: code/main_relocate.py
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697801169.118681
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.8.18
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
